package br.com.guiabolso.connector.common.code

object ErrorCode {

    const val MISSING_REQUIRED_PARAMETER = "MISSING_REQUIRED_PARAMETER"
    const val FAILED_DEPENDENCY = "FAILED_DEPENDENCY"
    const val TIMEOUT = "TIMEOUT"

    const val UNAUTHORIZED_USER = "UNAUTHORIZED_USER"
    const val EXPIRED_REFRESH_TOKEN = "EXPIRED_REFRESH_TOKEN"
    const val EXPIRED_AUTHORIZATION_CODE = "EXPIRED_AUTHORIZATION_CODE"

    const val CACHE_CONFIGURATION_ERROR = "CACHE_CONFIGURATION_ERROR"
}
