name: Publish docker image
on:
  release:
    types:
      - published
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag - ${{ github.event.release.tag_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Export project enviroment variables
        run: |
          echo "GUIABOLSO_CONNECTOR_VERSION=$(./gradlew properties --console=plain -q | grep "^version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "DATADOG_VERSION=$(./gradlew properties --console=plain -q | grep "^datadog-version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "SHORT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image with tags -> ${{ env.GUIABOLSO_CONNECTOR_VERSION }}, latest
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            guiabolso/guiabolso-connector:${{ env.GUIABOLSO_CONNECTOR_VERSION }}
            guiabolso/guiabolso-connector:latest
          build-args: |
            GUIABOLSO_CONNECTOR_VERSION=${{ env.GUIABOLSO_CONNECTOR_VERSION }}
            DATADOG_VERSION=${{ env.DATADOG_VERSION }}
            SHORT_COMMIT=${{ env.SHORT_COMMIT }}